version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:                                                                 
      - cd /tmp
      - git clone https://github.com/gara2000/continuous_delivery_on_s3.git
      - cd continuous_delivery_on_s3
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - rm -rf dist
      - ng build
      - aws s3 sync dist/continuous_delivery_app/browser/ s3://continuousdeliverybucket/ --region us-east-1 --delete
  post_build:
    commands:
      - rm -rf /tmp/*
      - echo Build completed on `date`
